feat: sign delegate with ununifi & keplr
UnUniFi/web-apps pull request #156
Opened 2022-05-11 09:30 UTC by Senna46

Send createDelegate Tx with Keplr or UnUniFi

- [x] Keplr
![keplr](https://user-images.githubusercontent.com/29295263/167822735-5a4e4fe2-1f69-4911-ac15-1eba722ebf25.gif)

- [x] UnUniFi (Legacy)
![legacy](https://user-images.githubusercontent.com/29295263/167826491-7dcd2247-95f3-4352-8abe-46e7dd08a005.gif)

2022-05-11 10:18 UTC, Senna46 commented
@mkXultra @taikiFurusyo 
Use https://github.com/UnUniFi/web-apps/tree/feature/delegate branch to check the behavior of Legacy and Keplr.
Now, Available only for Delagate.

2022-05-11 10:20 UTC, YasunoriMATSUOKA requested changes
@Senna46 
I commented on what I felt about this PR diff.
I would like to get a review from @mkXultra before implement other similar features.

2022-05-11 10:20 UTC, YasunoriMATSUOKA commented on projects/portal/src/app/models/cosmos/tx-common.service.ts
> +  }
I guess it is better to remove this function (or use this function to execute keplrAppService.signDirect in this function.)

```suggestion
```

2022-05-11 10:31 UTC, Senna46 commented on projects/portal/src/app/models/cosmos/tx-common.service.ts
> +    throw Error('Currently signing with Keplr is not supported!');
Changed! thx

2022-05-11 10:53 UTC, YasunoriMATSUOKA requested changes
@Senna46 
The following methods are not this PR diff, but it may be better to move the wallet related code from keplr.application.service to walletApplicationService.

- keplrSelectWallet
- openKeplrImportWalletDialog ... I guess openKeplrSelectWalletDialog is better.
- openConnectWalletCompleteDialog ... I guess you don't need implement this because same methods has already exists on WalletApplicationService.

2022-05-11 11:06 UTC, Senna46 commented
> @Senna46 The following methods are not this PR diff, but it may be better to move the wallet dialog related code from keplr.application.service to walletApplicationService.
> 
> * keplrSelectWallet
> * openKeplrImportWalletDialog ... I guess openKeplrSelectWalletDialog is better.
> * openConnectWalletCompleteDialog ... I guess you don't need implement this because same methods has already exists on WalletApplicationService.

Reconsider after merge as it will not affect UX and will complicate this PR.

2022-05-11 11:06 UTC, YasunoriMATSUOKA requested changes
@Senna46 
I missed another important point.

I guess now you are using cosmojs/launchpad. But it seems to support only  Cosmos SDK 0.37 (cosmoshub-3), 0.38 and 0.39 (Launchpad). ( 
by https://www.npmjs.com/package/@cosmjs/launchpad/v/0.24.0-alpha.3 )

I guess we should use cosmojs/stargate( https://www.npmjs.com/package/@cosmjs/stargate ). how do you think about it?

2022-05-11 11:25 UTC, YasunoriMATSUOKA commented
> @YasunoriMATSUOKA
> I am using this only for Decode and don't see any problem. Probably decode in base64.
> 
> I have not found a similar feature in stargate.
> https://github.com/cosmos/cosmjs/blob/main/packages/stargate/src/signingstargateclient.ts

If it's just base64 decoding, can you implement it without using cosmojs and remove cosmojs from package.json?
I would like to eliminate dependencies on libraries that only support older versions as soon as possible.

2022-05-11 11:38 UTC, YasunoriMATSUOKA commented
@Senna46 
I guess we should set `chainName` in `config.js` and use it in `suggestChain`.

examples

- UnUniFi
- UnUniFi (Beta)
- UnUniFi (Alpha)

![image](https://user-images.githubusercontent.com/55148923/167840463-78979a41-f023-466f-8208-367c2fc4ea92.png)

2022-05-12 02:43 UTC, mkXultra approved these changes

2022-05-12 05:07 UTC, merged