fix: bank query build error
UnUniFi/web-apps pull request #332
Opened 2023-02-07 04:20 UTC by KimuraYu45z

we can use this if we set 

```
denoms?: string[]
```

as `undefined`.

2023-02-07 04:21 UTC, KimuraYu45z commented
```
git cherry-pick 1a6411d
```

2023-02-07 04:38 UTC, Senna46 commented
Why use `declare const QueryApi: any | { balance(address: string, denom: string): Promise<any> };`?
Can't all queries use `cosmosclient.rest.bank`

2023-02-07 04:48 UTC, KimuraYu45z commented
This is a temporal fixing.
Currently all pages use with `denoms = undefined` so currently there is no problem.
After the update of `cosmos-client`, we will not have to use `QueryApi` directly so this code is completely temporal stuff.

2023-02-07 04:49 UTC, KimuraYu45z commented
We now just use `allBalance` that is exported by `cosmos-client` without `QueryApi`.
Now we don't use `balance` that is not exported by `cosmos-client` and inevitable to use `QueryApi` directly.

2023-02-07 07:52 UTC, Senna46 commented
Same problem as https://github.com/UnUniFi/web-apps/pull/327 ?
It's better to match.

2023-02-07 07:54 UTC, Senna46 requested changes

2023-02-07 07:54 UTC, Senna46 commented on projects/portal/src/app/models/cosmos/bank.query.service.ts
> +              new QueryApi(undefined, sdk.url)
I do not reccomend use QueryApi bacause of  using `any` type.

2023-02-08 02:24 UTC, KimuraYu45z commented
https://github.com/UnUniFi/web-apps/pull/327/commits/dae1fbc809558d4738fabec843bf354e4d533165

2023-02-08 02:24 UTC, closed without merging