New design 0321
UnUniFi/web-apps pull request #382
Opened 2023-03-20 16:51 UTC by Senna46

#375
New Balance Page (Top Page)
Fixed drawer not closing issue

Not yet tested on mobile

2023-03-20 23:13 UTC, KimuraYu45z requested changes
Balanceに関してはBTC, USDC以外も増えうるので、statsでなくtableでいいかもしれない
あと将来的にはトークンごとにアイコン用意して表示するのが理想でもあるのでその枠も

2023-03-20 23:47 UTC, KimuraYu45z requested changes
あとアドレスのコピー機能もほしい

2023-03-21 00:59 UTC, Senna46 commented
> Balanceに関してはBTC, USDC以外も増えうるので、statsでなくtableでいいかもしれない
> あと将来的にはトークンごとにアイコン用意して表示するのが理想でもあるのでその枠も

tableは特にオーバーフローの表示が微妙でstatsにしてます
flex-wrapにすればトークン増えてもとかに問題なく表示できるはずです



> あとアドレスのコピー機能もほしい

アドレスコピーはバッジを押した時とinfo開いた中でできるようにはしていますが、もっと明示的に置いたほうが良いかもですね

2023-03-21 02:53 UTC, Senna46 commented
Some Redesign
- Top Page
![screencapture-localhost-4200-portal-2023-03-21-11_48_58](https://user-images.githubusercontent.com/29295263/226507201-04a9e6d2-e010-452b-a38d-58c34474b5f3.png)
![screencapture-localhost-4200-portal-2023-03-21-11_49_23](https://user-images.githubusercontent.com/29295263/226507206-469fa83b-ec9a-4e26-be80-9c383eec881d.png)

- Pool 
![screencapture-localhost-4200-portal-derivatives-pool-2023-03-21-11_51_08](https://user-images.githubusercontent.com/29295263/226507376-a23752c5-9629-4402-84bf-0335a3d776c3.png)

& Tradingview widget, NFT Mint Class ID, etc.

2023-03-22 06:42 UTC, merged