feat: redesign header&bar
UnUniFi/web-apps pull request #416
Opened 2023-03-28 11:43 UTC by Senna46

It was divided into three paths, each redesigned.

1. utilities
2. nft-backed-loan
3. derivatives

![スクリーンショット 2023-03-28 195649](https://user-images.githubusercontent.com/29295263/228225006-4a9ed320-77fe-4565-9102-4a40d48148db.png)
![スクリーンショット 2023-03-28 195630](https://user-images.githubusercontent.com/29295263/228225020-29557cc9-f064-42da-8e25-fe0938b52926.png)
![スクリーンショット 2023-03-28 195730](https://user-images.githubusercontent.com/29295263/228225028-2e2daafc-0591-4c94-a8ec-e6e445f8c0ac.png)
![スクリーンショット 2023-03-28 204157](https://user-images.githubusercontent.com/29295263/228225191-8e2a25d0-cccc-4e12-967b-2eccfaca0648.png)

2023-03-28 13:32 UTC, Senna46 commented
close #415
Sidebar always open on laptops and above

2023-03-29 05:22 UTC, mkXultra commented
https://github.com/UnUniFi/lab-test/issues/86

2023-03-29 14:13 UTC, KimuraYu45z requested changes

2023-03-29 14:13 UTC, KimuraYu45z commented on projects/portal/src/app/views/tools/app-tool/app-tool.component.ts
> +      { name: 'Utilities', link: '/', icon: 'account_balance_wallet' },
`assistant` is better for icon

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:assistant:FILL@0;wght@400;GRAD@0;opsz@48

2023-03-29 14:13 UTC, KimuraYu45z commented on projects/portal/src/app/views/tools/app-tool/app-tool.component.ts
> +      { name: 'NFT Backed Loan', link: '/nft-backed-loan', icon: 'photo_library' },
`loyalty` is better for icon I think
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:loyalty:FILL@0;wght@400;GRAD@0;opsz@48

NFT is not only for JPEG

2023-03-30 07:09 UTC, KimuraYu45z approved these changes
LGTM

2023-03-30 07:12 UTC, merged